# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: One Bonsai
email: skylar.saveland@gmail.com
description: >-
  One Bonsai is a philosophy for software productivity
baseurl: "bonsai"
# Use for local testing remote theme assets don't seem to work with the
# same config for remote and local
# baseurl: ""
url: "https://skyl.github.io"
# url: https://github.com/skyl/bonsai
# repo_url: https://github.com/skyl/bonsai
twitter_username: _skyl
github_username:  skyl
repository: skyl/bonsai

# Build settings
# markdown: kramdown
remote_theme: skyl/jekyll-theme-rtd
# remote_theme: carlosperate/jekyll-theme-rtd
# remote_theme: sohn3363/sohn3363.github.io
# remote_theme: rundocs/jekyll-rtd-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
